/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exercicio.atleta.heranca;

/**
 *
 * @author phfic
 */
public class TelaCorredor extends javax.swing.JFrame {

    /**
     * Creates new form TelaCorredor
     */
    public TelaCorredor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMaratonista = new javax.swing.JButton();
        btnVelocista = new javax.swing.JButton();
        btnTriatleta = new javax.swing.JButton();
        lblTipoFisico = new javax.swing.JLabel();
        lblPerformance = new javax.swing.JLabel();
        lblTempoMedio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnMaratonista.setText("Nasce um Maratonista");
        btnMaratonista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaratonistaActionPerformed(evt);
            }
        });

        btnVelocista.setText("Nasce um Velocista");
        btnVelocista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVelocistaActionPerformed(evt);
            }
        });

        btnTriatleta.setText("Nasce um Triatleta");
        btnTriatleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTriatletaActionPerformed(evt);
            }
        });

        lblTipoFisico.setText("Tipo físico: ");

        lblPerformance.setText("Performance: ");

        lblTempoMedio.setText("Tempo médio correndo: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnMaratonista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTriatleta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVelocista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblTipoFisico)
                    .addComponent(lblPerformance)
                    .addComponent(lblTempoMedio))
                .addContainerGap(236, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnMaratonista)
                .addGap(18, 18, 18)
                .addComponent(btnVelocista)
                .addGap(18, 18, 18)
                .addComponent(btnTriatleta)
                .addGap(18, 18, 18)
                .addComponent(lblTipoFisico)
                .addGap(18, 18, 18)
                .addComponent(lblPerformance)
                .addGap(18, 18, 18)
                .addComponent(lblTempoMedio)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMaratonistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaratonistaActionPerformed
        // horas > minutos > segundos
        Maratonista m = new Maratonista("Tipo físico: Magrinho", "Performance: Corre por horas", (60*2)*60.0);
        lblTipoFisico.setText(m.getTipoFisico());
        lblPerformance.setText(m.getPerformance());
        lblTempoMedio.setText(String.format("Tempo médio correndo: %.2f segundos", m.getTempoMedio()));
    }//GEN-LAST:event_btnMaratonistaActionPerformed

    private void btnVelocistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVelocistaActionPerformed
        Velocista v = new Velocista ("Tipo físico: Musculoso", "Performance: Corre por alguns segundos", 30.0);
        lblTipoFisico.setText(v.getTipoFisico());
        lblPerformance.setText(v.getPerformance());
        lblTempoMedio.setText(String.format("Tempo médio correndo: %.2f segundos", v.getTempoMedio()));
    }//GEN-LAST:event_btnVelocistaActionPerformed

    private void btnTriatletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTriatletaActionPerformed
        Triatleta t = new Triatleta ("Tipo físico: Torneado", "Performance: Corre por até uma hora", 45*60.0);
        lblTipoFisico.setText(t.getTipoFisico());
        lblPerformance.setText(t.getPerformance());
        lblTempoMedio.setText(String.format("Tempo médio correndo: %.2f segundos", t.getTempoMedio()));
    }//GEN-LAST:event_btnTriatletaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCorredor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCorredor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCorredor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCorredor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCorredor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMaratonista;
    private javax.swing.JButton btnTriatleta;
    private javax.swing.JButton btnVelocista;
    private javax.swing.JLabel lblPerformance;
    private javax.swing.JLabel lblTempoMedio;
    private javax.swing.JLabel lblTipoFisico;
    // End of variables declaration//GEN-END:variables
}
